- name: Create VPC
  ec2_vpc_net:
    name: "{{ vpc_name }}"
    cidr_block: "{{ vpc_cidr_block }}"
    region: "{{ aws_region }}"
    aws_access_key:   "{{ aws_access_key }}"
    aws_secret_key:   "{{ aws_secret_key }}"
    state: present
  register: my_vpc

- name: Set VPC ID in variable
  set_fact:
    vpc_id: "{{ my_vpc.vpc.id }}"

- name: Create public subnet
  ec2_vpc_subnet:
    state: "present"
    vpc_id: "{{ vpc_id }}"
    cidr: "{{ public_subnet_1_cidr }}"
    az: "{{ aws_region }}a"
    region: "{{ aws_region }}"
    aws_access_key:   "{{ aws_access_key }}"
    aws_secret_key:   "{{ aws_secret_key }}"
    resource_tags:
      Name: "Public Subnet"
  register: my_public_subnet 

- name: Set public subnet ID in variable
  set_fact:
    public_subnet_id: "{{ my_public_subnet.subnet.id }}"

- name: Creat Internet Gateway for VPC
  ec2_vpc_igw: 
    vpc_id: "{{ vpc_id }}"
    region: "{{ aws_region }}"
    aws_access_key:   "{{ aws_access_key }}"
    aws_secret_key:   "{{ aws_secret_key }}"
    state: "present"
  register: my_vpc_igw

- name: Set Internet Gateway ID in variable
  set_fact:
    igw_id: "{{ my_vpc_igw.gateway_id }}"

- name: Set up public subnet route table
  ec2_vpc_route_table:
    vpc_id: "{{ vpc_id }}"
    region: "{{ aws_region }}"
    aws_access_key:   "{{ aws_access_key }}"
    aws_secret_key:   "{{ aws_secret_key }}"
    tags:
      Name: "Public"
    subnets:
      - "{{ public_subnet_id }}"
    routes:
      - dest: "0.0.0.0/0"
        gateway_id: "{{ igw_id }}"


# - name: Create Main Security Group
#   ec2_group:
#     name: "My Security Group"
#     description: "My Security Group"
#     vpc_id: "{{ vpc_id }}"
#     region: "{{ aws_region }}"
#     aws_access_key:   "{{ aws_access_key }}"
#     aws_secret_key:   "{{ aws_secret_key }}"
#     rules:
#       - proto: "tcp"
#         from_port: "22"
#         to_port: "22"
#         cidr_ip: "{{ my_ip }}/32"